### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by spkprs**
add text, strings ;)

### CODE REVIEW

**Comment by tibbi** [comment]
where did you get those 2 new strings from? Every string should be every language file, else it becomes a mess

**Comment by spkprs** [comment]
After decompile Gallery.apk  string line 1159 Sent from S.K. From: Tibor KaputaSent: Τετάρτη, 7 Ιουλίου 2021 00:36To: SimpleMobileTools/Simple-GalleryCc: spkprs; AuthorSubject: Re: [SimpleMobileTools/Simple-Gallery] Update strings.xml (#2176) where did you get those 2 new strings from? Every string should be every language file, else it becomes a mess—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by spkprs** [comment]
I'm not dev, so ....

**Comment by tibbi** [comment]
ye I wll take a look at it, just not working on the gallery now. Ill reopen so I wont forget

**Comment by tibbi** [comment]
there is no circular crop in the editor though, right? Or do you see pesdk_transform_button_circleCropMask anywhere?

**Pull request merged**
