### PR TITLE
fix the dispearance of search actionviews

### PR DESCRIPTION
**Pull request by KnIfER**
https://github.com/SimpleMobileTools/Simple-Gallery/issues/1279

### CODE REVIEW

**Comment by tibbi** [comment]
oh gosh, this is a really bad and ugly code. Thanks though

**Comment by KnIfER** [comment]
I don't understand, is this causing side effects?

**Comment by privatmamtora** [comment]
@tibbi So is this issue fixed? (Issues still present in v 6.9.6)

**Comment by tibbi** [comment]
not fixed yet

**Comment by privatmamtora** [comment]
@tibbi Should I create an issue for it? (Just so that it is listed somewhere)

**Comment by tibbi** [comment]
this pull request is about https://github.com/SimpleMobileTools/Simple-Gallery/issues/1279 I guess, create some other one if it is something different

**Comment by privatmamtora** [comment]
#1279 has 2 things mentioned within it, which I split in the comment. One is a Feature Request and another is an Issue.
I will create another issue for it.

**Pull request closed without merging**
