### PR TITLE
Update German FAQs

### PR DESCRIPTION
**Pull request by kniddl**
"Du" is the personal form of address and "Sie" is the honorific. Which do you prefer? I saw that in French the honorific form of address was chosen but in German not.

### CODE REVIEW

**Comment by tibbi** [comment]
I dont know, just make it consistent in the whole file

**Comment by kniddl** [comment]
A clear stance would be easier since I am not the only translator. As long as people are interpreting the you differently there will always be inconsistencies. It's the choice between casual or polite and I can't make the decision for, sorry.

**Comment by tibbi** [comment]
Im not from Germany, I dont know what is the usual way for doing it. Just check other strings how is it done, no need to change it.

**Comment by tibbi** [comment]
Im using the more polite way, but or example in Hungary they use the casual version more often. Just leave the German strings as they are then. Thanks

**Comment by kniddl** [comment]
Ok, I will just watch to have it consistent within an app and not across all.  And I will use the polite form in my translation then. Thanks for taking your time and thanks for the apps; they are very useful 😄.

**Pull request merged**
