### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Chefski**
Update Google Play Badge

### CODE REVIEW

**Comment by tibbi** [comment]
I dont want to update it

**Comment by Chefski** [comment]
That's not following the Badge Guidelines
image

**Comment by tibbi** [comment]
I still dont want to rely on a remote icon though. They can break the link anytime.

**Comment by kmein** [comment]
@tibbi well, can't you just replace https://simplemobiletools.com/images/button-google-play.svg by the new icon then?

**Pull request closed without merging**
