### PR TITLE
Add option to play videos externally

### PR DESCRIPTION
**Pull request by TheRandomLabs**
After scrolling from another picture/video to a video then clicking on the play button, Simple Gallery by default uses ExoPlayer. I've implemented an option that allows the user to change this behavior.

### CODE REVIEW

**Comment by tibbi** [comment]
thanks, but I dont want to add such redundant checks, nobody requested it so far. There is already an "Open with" button in case someone wants to use another app.

**Comment by TheRandomLabs** [comment]
Fair enough. What about changing the open with button to not force an app
chooser?

Le jeu. 13 déc. 2018 à 02:19, Tibor Kaputa <notifications@github.com> a
écrit :

**Comment by tibbi** [comment]
I want to keep it as it is for now, it might be changed in the future

**Comment by TheRandomLabs** [comment]
Alright, thanks!

**Comment by tibbi** [comment]
so it turns out that I will use that way of playing videos indeed, but Ill make it mandatory, not optional. It would fix a few glitches that I couldnt solve other way.

**Comment by TheRandomLabs** [comment]
Cool, great to hear!

**Pull request closed without merging**
