### PR TITLE
Use Java 8 Date/Time API.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
* Enable [Java 8 API desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) and use [the Java 8 Date/Time API](https://www.baeldung.com/java-8-date-time-intro).
* Enabling API desugaring also includes [bug fixes](https://issuetracker.google.com/issues/37042460) for `ConcurrentHashMap` on Android Lollipop.

### CODE REVIEW

**Comment by tibbi** [comment]
what benefits does it bring?

**Comment by Isira-Seneviratne** [comment]
> what benefits does it bring?

Working with dates and times is much easier.

**Comment by tibbi** [comment]
but I mean in this specific case. Does it fix any bug? I dont want to risk changing code just for fun.

**Comment by Isira-Seneviratne** [comment]
> but I mean in this specific case. Does it fix any bug? I dont want to risk changing code just for fun.

I tested it out with the grouping functionality, and didn't find any issues.

**Comment by tibbi** [comment]
I dont see any related crashes, so Ill pass on this. Thanks though

**Pull request closed without merging**
