### PR TITLE
Add proprietary and foss product flavors

### LINKED ISSUE #1706: F-Droid NoSourceSince
F-Droid marked your app with `This app has features you may not like: NoSourceSince`.
Do you know why and how to fix this? :)

Is this, because of the license change? Or because of the new photo editor?

Latest release was 6.10.8 on F-Droid.

[F-Droid Link](https://f-droid.org/en/packages/com.simplemobiletools.gallery.pro/).

### PR DESCRIPTION
**Pull request by ForgottenUmbrella**
The introduction of the proprietary PhotoEditor SDK prevented this app from
being truly free and open source, and so F-Droid could no longer build the app.
By adding a licensing flavor dimension, we segregate the non-FOSS code to a
separate version, while providing a FOSS version without the editor.

To build the proprietary version, select one of the proprietary build variants
from Build Variants pane in Android Studio (on the left side of the window).

Fixes #1706.

### CODE REVIEW

**Comment by tibbi** [comment]
Have you tested if it works well with f-droid?

**Comment by licaon-kter** [comment]
Pretty please don't change the appid yet **again**...

**Comment by licaon-kter** [comment]
FYI, builds fine for F-Droid. ;)

**Comment by tibbi** [comment]
ok, make it consistent with other apps though. By default the PhotoEditorSDK should be included, the extra steps should be needed for removing it. Not the other way around

**Comment by tibbi** [comment]
actually it looks ok, I just had to refresh the project build types. @licaon-kter not sure what you mean with the app ID. You want to change something?

**Comment by tibbi** [comment]
will accept it for now, thanks

**Comment by licaon-kter** [comment]
Please revert it...

**Comment by tibbi** [comment]
okay, so do whatever is needed on F-droid please, I'm going to release the new version 6.13.0 now. I also added version codes to the generated .apk files, so the new filename will look like "gallery-295-foss-release.apk". Not sure if you have to change something there manually, all apps will eventually get the version code update.

**Comment by licaon-kter** [comment]
We'll see, thanks.

**Comment by klawdhfzasjhaa** [comment]
Thank you @ForgottenUmbrella @tibbi @licaon-kter !

**Pull request merged**
