### PR TITLE
Always use ARGB_8888 to avoid artifacts in images

### LINKED ISSUE #343: image is shown with weird artifacts
This applications is awesome. 

Unfortunately I've noticed a slight issue. The following image:

spheres sunset 1080x1920

is shown in Gallery like this:

(notice the artifacts in the grey sky?)

screenshot_20170830-212702

### PR DESCRIPTION
**Pull request by esensar**
This closes #343

### CODE REVIEW

**Comment by esensar** [comment]
Do we have a reason to avoid ARGB_8888 when high quality is not enabled? Will it really affect performance that much? I don't have devices at hand to test this out, but looks like it would just potentially slow down the loading in some cases.

**Comment by tibbi** [comment]
I dont remember why was it like that, will try testing it to see the performance and quality

**Comment by tibbi** [comment]
I get compilation error e: .../simplemobiletools/Simple-Gallery/app/src/main/kotlin/com/simplemobiletools/gallery/pro/extensions/Context.kt: (500, 92): No type arguments expected for annotation class Target

**Comment by tibbi** [comment]
actually getting it on master too, it works for you?

**Comment by tibbi** [comment]
nevermind, it was fixed on master

**Comment by tibbi** [comment]
This doesnt really improve the quality to me, and it will likely have some performance issues too. I think improving the quality needs more fundamental work, ideally merging glide, picasso and subsamplingscaleimageview into 1 library, or find one that already exists. I wasnt researching it for ages, not sure what are the most modern ways of displaying images.

**Comment by tibbi** [comment]
that setting lags though, even on my highest top notch device zooming in bigger photos like panoramic ones are lagging.. This needs some more advanced tweaking.

**Comment by esensar** [comment]
Alright, I will have to check it out then. I haven't tried with panoramic photos.

**Comment by tibbi** [comment]
I mean not clicking on the center icon to open the panoramic view, just zoom and look around the photo like it was a casual photo

**Pull request merged**
