### PR TITLE
add oreo adaptive icon

### PR DESCRIPTION
**Pull request by fiepi**

### CODE REVIEW

**Comment by tibbi** [comment]
I dont want to update to target sdk 26 yet, it breaks a lot of things. I will fix them within 1-2 weeks, Ill keep the pull request here meanwhile. Thanks

**Comment by fiepi** [comment]
at target sdk 23, adaptive icon still work

**Comment by tibbi** [comment]
and how about compileSdkVersion and buildToolsVersion? Do they have to be updated? I havent tested them yet. Also I dont have any Android 8 for testing.

**Comment by fiepi** [comment]
I just tested, even in build tools 25, still work. :smiley:

**Comment by tibbi** [comment]
okay cool, thanks then :)

**Pull request merged**
