### PR TITLE
Dutch

### PR DESCRIPTION
**Pull request by ltGuillaume**
Did you do some kind of marketing course? 😜😘

### CODE REVIEW

**Comment by tibbi** [comment]
Im always AB testing something and apply it if the difference is huge enough :)
abtesting

**Comment by ltGuillaume** [comment]
That's nice stuff. Is this an interface that's supplied by Google/Play Store?

**Comment by tibbi** [comment]
ye, the developer console

**Comment by ltGuillaume** [comment]
Cool! And yeah, I can imagine these things become even more important when it comes to projects like these, which have so much competition.

More or less related, the Gallery app in F-Droid shows as "Simple Gallery Pro: Photo Mana" (instead of "Manager"). This cut-off is rather odd and I tend to misread it as "Photo Mania" 😁

**Comment by tibbi** [comment]
F-droid has more issues, sadly they dont care about the project anymore. Not much work has been done over the last years.

**Comment by ltGuillaume** [comment]
Yeah, true, seems like it's gone stale.

**Pull request merged**
