### PR TITLE
#505 remembering last video position

### PR DESCRIPTION
**Pull request by mathevs**
#505 adding feature. Saving last video position and storing it to the config. After starting video again it will continue from last remembered position.

### CODE REVIEW

**Comment by tibbi** [comment]
make it optional and disabled by default please, plus fix the code formatting (spaces) and conflicts. Thanks

**Comment by mathevs** [comment]
It is ok now, but some strings need to be translated.

**Comment by tibbi** [comment]
you have to put the string in every language file anyway, even if obviously in english

**Comment by mathevs** [comment]
I put this string to every language string.xml.

**Comment by mathevs** [comment]
I already moved it to the right position https://github.com/SimpleMobileTools/Simple-Gallery/pull/1038/commits/494e71e5e34a88255033e449cec47ce407ddeba0

**Comment by tibbi** [comment]
aha I didnt see it. Thanks, looks good, it just doesnt work properly if there are multiple video files near each other. Ill fix it.

**Pull request merged**
