### PR TITLE
Use coroutines.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
Use Kotlin's [coroutines](https://kotlinlang.org/docs/reference/coroutines-overview.html) to improve performance, particularly when scrolling through folders containing lots of images.

### CODE REVIEW

**Comment by tibbi** [comment]
Thanks for the effort, but it doesnt really improve the performance to me, nor I see why would it. Changing this amount of code in 27 files at once is way too risky, plus you removed some try/catch blocks for no reason.

**Comment by Isira-Seneviratne** [comment]
> Thanks for the effort, but it doesnt really improve the performance to me, nor I see why would it. Changing this amount of code in 27 files at once is way too risky, plus you removed some try/catch blocks for no reason.

Exception handling isn't mandatory in Kotlin, and those blocks weren't logging the exception or doing anything else.

**Comment by tibbi** [comment]
all try/catch blocks were there for a reason, I saw crashes there in crashlogs

**Comment by Isira-Seneviratne** [comment]
> all try/catch blocks were there for a reason, I saw crashes there in crashlogs

Oh, my bad

**Comment by Isira-Seneviratne** [comment]
How about if I broke it up into smaller changes?

**Comment by tibbi** [comment]
well if they will be really smaller ones, we could try. I want to release a new version with few changes too, so it wont be all released together.

**Pull request closed without merging**
