### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by AlbatorV**
Wher I can find these strings ?
<string name="set_as_default_folder">Définir comme dossier par défaut</string>
<string name="unset_as_default_folder">Ne plus définir comme dossier par défaut</string>

### CODE REVIEW

**Comment by tibbi** [comment]
setting a default folder is a new feature, you need 6.17.3 for it. Just open a folder and it will be at the top menu, above Create new folder.

**Comment by AlbatorV** [comment]
ok, but defaut for ?

**Comment by tibbi** [comment]
for opening when the app is launched

**Comment by AlbatorV** [comment]
Oh yes, nice feature.
And I love new thumbs style.
Thanks

**Comment by tibbi** [comment]
thanks

**Pull request merged**
